### ISSUE TITLE
Can you upload a .cbplugin version?

### ISSUE THREAD

**Issue by Jecvay** [zmj64351508/cbvike#1]
Compiling is a complex work.

**Comment by bouchtaoui-dev** [comment]
Yes, we would like to use this library, but it doesn't make sense to download complete wxWidgets and CodeBlocks sources to compile this plugin. Downloading a cbplugin file should be sufficient. I hope you can provide us your great work as a cbplugin that is compatible with the standard Code:Blocks for Windows.

**Comment by zmj64351508** [comment]
I‘ve upload a binary for 13.12
https://github.com/zmj64351508/cbvike/releases

When trying to install it in 13.12, it will say "One or more plugins were not installed successfully". But it doesn't matter, restart your C::B and you will see it has been installed successfully. Enjoy it.

**Comment by Jecvay** [comment]
Thanks!

**Comment by bouchtaoui-dev** [comment]
Great! Thnx

**Comment by csJd** [comment]
I'm trying to install it in 16.01 but it shows:
SDK version mismatch for cbVike (1.19.0). Expecting 1.29.0
Loaded 61 plugins
