### ISSUE TITLE
File 'cbVike.so' not found when installing.

### ISSUE THREAD

**Issue by jackyyf** [zmj64351508/cbvike#2]
Plugin was built successfully, but when installing, codeblocks keep blaming that:
    `File 'cbVike.so' not found in plugin '/tmp/cbvike/build/bin_unix/release/cbVike.cbplugin'`

Is there any step I missed?

**Comment by zmj64351508** [comment]
Maybe I made a mistake in the filename. Please unpack cbVike.cbplugin using unzip and see whether there is libcbvike.so in it. If so, please rename libcbvike.so to cbVike.so

**Comment by jackyyf** [comment]
It seems there are only `cbVike.zip` inside cbplugin file. And inside release directory, `libcbVike.so` instead of `cbVike.so` exists. Manually renamed libcbVike.so to cbVike.so and add to cbplugin file, and it works :)

Thanks for your help :)
